### ISSUE TITLE
Filter does not work

### ISSUE THREAD

**Issue by raba34** [ndunand/moodle-filter_html5avtomp4#1]
Hello,

I am using Moodle 3.8 on Ubuntu 18.04 LTS. Unfortunately the filter has no effect. The same message appears in the task log every minute:

```
Execute scheduled task: Process reencoding non-MP4 files (filter_html5avtomp4\task\processjobs_task)
... started 14:54:04. Current memory use 33.1MB.
found 0 jobs
... used 1 dbqueries
... used 0.0016191005706787 seconds
Scheduled task complete: Process reencoding non-MP4 files (filter_html5avtomp4\task\processjobs_task)
```

I have the impression that the conversion is not taking place. In Safari the file does not play. Instead, the *.OGG file is offered for download.

There is a single error message. When I use phpMyAdmin to output the contents of the "mdl_filter_html5avtomp4_jobs" table in the Moodle database, phpMyAdmin displays the following error message:

```
Warning in ./libraries/sql.lib.php#613
count(): Parameter must be an array or an object that implements Countable

```
Could that be the cause?

Best regards,
Ralph

**Comment by ndunand** [comment]
Hello.

The warning is normal although I should fix this; it’s because there are no jobs found. This is expected as audio files are processed on the fly without relying on scheduled tasks.

However the fact that this audio file is not converted is weird. What are the plugin settings?

**Comment by raba34** [comment]
Hello,

thank you for the quick response.

In the meantime I have continued to experiment and I believe I have found the reason.

I have done them all with TinyMCE so far. Now I switched to Atto. After that the problems disappeared.

I have always used TinyMCE but I don't see a big difference to Atto. So I will set Atto as default editor. Let's see if my users notice anything.

Best regards,
Ralph

**Comment by ndunand** [comment]
Hello Ralph,

Thanks for reporting back, I would never have thought of that. That could be of the exact way TinyMCE inserts `<audio>` HTML tags. This is checked by this filter here: https://github.com/ndunand/moodle-filter_html5avtomp4/blob/master/filter.php#L54 . We can probably get it to work with TinyMCE quite easily if you need to.

In the meantime I'll add to the documentation for the next release that this plugin works with tags generated by Atto only.

**Comment by raba34** [comment]
Hello Nicolas,

thank you again for the quick response. For me it is sufficient that the filter works with atto.

I would like to point out how my error report was created. I read in a discussion on moodle.org that several members complained that videos created with RecordRTC are not playable with Safari. The group suggested using your filter. But none of them seemed to have their own installation to try it out directly. So I was the only one who could implement the suggestion immediately. I am also the only one who could report problems. So it is quite possible that these problems only occur during my installation.

I have reported my problems and their solution to the group.

Best regards,
Ralph

**Comment by ndunand** [comment]
Thanks for this, could you please link the relevant discussion so I can jump in ?

**Comment by raba34** [comment]
This is the link to the discussion:

https://moodle.org/mod/forum/discuss.php?d=401254
