### ISSUE TITLE
Compatibility with Moodle 4.1

### ISSUE THREAD

**Issue by ngskmoodler** [ndunand/moodle-filter_html5avtomp4#11]
Dear Nicolas,
The page https://moodle.org/plugins/filter_html5avtomp4/versions
says that the plugin is compatible with Moodle 3.7-3.11. That should mean it is not compatible with 4.1. Is that correct? If so, is there any plan to make it compatible with 4.1? I am using it on 3.9 and would like to know if I can continue to use it after a planned site upgrade to 4.1. 
On https://moodle.org/plugins/filter_html5avtomp4, I saw that a user reports that the plugin disables itself on 4.1 and became concerned.
This may not be the right place to post my query, but I could not find any other way to contact you.
Thank you for your time and attention.
Sergio

**Comment by ndunand** [comment]
Dear Sergio,
In our testing, the modifications made in Moodle 4.x documented in https://tracker.moodle.org/browse/MDL-65943 show that my plugin is no longer necessary. Si even though it should keep working, videos recorded in any format should now play back seamlessly in Safari (mobile or desktop) without the help of this filter. You can therefore safely uninstall this plugin in Moodle 4.x.

**Comment by ngskmoodler** [comment]
Dear Nicolas,

Thank you very much for the prompt reply and reference. Since I am a language teacher who uses Moodle rather than an IT specialist, I will recapitulate what I believe I understand. It is very important for me to be sure I understand well to plan my courses properly. If I am wrong, I wonder if you could be so kind as to correct me. 

1. At the moment, I record audio with RecordRTC on on my Windows computer and my students can play it in Safari, Firefox, Chrome, and Edge on their iOS devices because your filter, along with FFMPEG, converts it from OGG to M4A. After upgrading to Moodle 4.1, my students should be able to listen to the audio without the help of your filter. I will not need FFMPEG either. 

2. At the moment, if I record video with RecordRTC on my Windows computer, my students cannot play it on iOS devices. Although the video is converted from WebM to MP4 by your filter, they see a message that says that it is not compatible. (In my testing, it does not matter if I use Edge, Chrome, or Firefox on my computer, and if they use Safari, Edge, Chrome, or Firefox on their mobiles). However, after upgrading to 4.1, the videos I record with RecordRTC should be viewable on iOS devices. 

4.  At the moment, if I record audio with RecordRTC in any browser on an iOS device, I can play it back on my computer, but I cannot play it back in any browser on the iOS device (and my students could not do it on their iOS devices either). This is a different issue that was not addressed by your plugin and remains unsolved in Moodle 4.1. https://tracker.moodle.org/browse/MDL-62540

5. At the moment, if I record video with RecordRTC on an iOS device, I can play the recording back on my computer, but I can also play it back on the iOS device if I use Safari or Firefox, and the same thing could be done by my students. This should continue to be possible in Moodle 4.1 even without your filter. 

6. If I record video on an iOS device, there is no live view, which makes it inconvenient to frame the subject. (There is live view on iPadOS). This is an issue that remains unsolved.    

Thank you in advance for your kind assistance and also many thanks for developing the plugin. It has been very useful to me. 

Best regards,  

Sergio

**Comment by ngskmoodler** [comment]
Dear Nicolas,
Thank you very much for your prompt reply.
Best regards,
Sergio
