### ISSUE TITLE
Development inquiry

### ISSUE THREAD

**Issue by Tottebee** [ndunand/moodle-filter_html5avtomp4#4]
Hi,
The redundancy of the files is a big problem because videos are normally the biggest files.
Is there a possibilitiy for you to program a cleaning function in the filter to delete the old files?
I'm working for the State of Baden Wuerttemberg in Germany.So if you need to payed for the development, please make an offer for your work. It would be really helpful to have the delete function included for proper data keeping.
regards
Thorsten

**Comment by ndunand** [comment]
Hi, we're looking into this, documenting in #3

**Comment by ndunand** [comment]
merging and about to release new version including this feature, see #5
